name: Hello World

on:
  workflow_dispatch:
    inputs:
      person:
        description: Name to greet
        required: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.person }}!"
