name: Premium Runner Test

on:
  workflow_dispatch:

jobs:
  test-ubuntu-8core:
    name: Ubuntu 22.04 8-Core
    runs-on: ubuntu-22.04-8core
    steps:
      - run: echo "Hello from ubuntu-22.04-8core"

  test-ubuntu-24-8core:
    name: Ubuntu 24.04 8-Core
    runs-on: ubuntu-24.04-8core
    steps:
      - run: echo "Hello from ubuntu-24.04-8core"

  test-ubuntu-16core:
    name: Ubuntu 22.04 16-Core
    runs-on: ubuntu-22.04-16core
    steps:
      - run: echo "Hello from ubuntu-22.04-16core"

  test-ubuntu-32core:
    name: Ubuntu 22.04 32-Core
    runs-on: ubuntu-22.04-32core
    steps:
      - run: echo "Hello from ubuntu-22.04-32core"

  test-windows-8core:
    name: Windows 2022 8-Core
    runs-on: windows-2022-8core
    steps:
      - run: echo "Hello from windows-2022-8core"

  test-macos:
    name: macOS 13 XL
    runs-on: macos-13-xl
    steps:
      - run: echo "Hello from macos-13-xl"
