name: ratelimit

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  RPC_URL: http://slc.rpc.orbitflare.com

jobs:
  ratelimit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ratelimit

      - name: Check rate limits
        working-directory: ratelimit
        run: cargo run --release
        env:
          KEY_1: ${{ secrets.KEY_1 }}
          KEY_2: ${{ secrets.KEY_2 }}
          KEY_3: ${{ secrets.KEY_3 }}
          KEY_4: ${{ secrets.KEY_4 }}
