name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ratelimit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - name: Rate limit test - mainnet-beta
        run: ./target/release/hello-world "https://api.mainnet-beta.solana.com/"
      - name: Rate limit test - mainnet
        run: ./target/release/hello-world "https://api.mainnet.solana.com/"
