name: SLC RPC Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 10 --max-concurrent 10 --output ./blocks_10x10
        env:
          KEY_1: ${{ secrets.KEY_1 }}
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 10 --max-concurrent 20 --output ./blocks_10x20
        env:
          KEY_1: ${{ secrets.KEY_1 }}
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 10 --max-concurrent 30 --output ./blocks_10x30
        env:
          KEY_1: ${{ secrets.KEY_1 }}
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 20 --max-concurrent 10 --output ./blocks_20x10
        env:
          KEY_1: ${{ secrets.KEY_1 }}
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 20 --max-concurrent 20 --output ./blocks_20x20
        env:
          KEY_1: ${{ secrets.KEY_1 }}
      - run: ./target/release/solana-backfill --rpc "http://slc.rpc.orbitflare.com" --api-key "$KEY_1" --from-latest 1000 --batch-size 20 --max-concurrent 30 --output ./blocks_20x30
        env:
          KEY_1: ${{ secrets.KEY_1 }}
