name: test-release-create

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download release.zip
        run: |
          curl -L -o release.zip \
            "https://github.com/devakapatel/files/releases/download/1/release.zip"
          ls -lh release.zip

      - uses: actions/upload-artifact@v4
        with:
          name: fetched-release
          path: release.zip
